### ISSUE TITLE
Couldn't  run successful

### ISSUE THREAD

**Issue by IOLOII** [teamstarter/gsg-boilerplate#2]
step1 : yarn // install dependence

ste2:  yarn dev

error :
```shell
$ yarn dev
yarn run v1.22.21
warning ..\..\..\package.json: No license field
$ pm2 delete all -s; DEBUG=* pm2 startOrReload ecosystem.config.js && pm2 start react-scripts --name web -- start

  error: unknown option `-;'

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

then , I try  to fix just use this command:
```shell
pm2 startOrReload ecosystem.config.js && pm2 start react-scripts --name web -- start
```
error log
```shell
C:\Users\EDY\.pm2\logs\web-error.log last 15 lines:
1|web      | C:\USERS\EDY\DOCUMENTS\REPOS\GSG-BOILERPLATE\NODE_MODULES\.BIN\REACT-SCRIPTS.CMD:1
1|web      | @IF EXIST "%~dp0\node.exe" (
1|web      | ^
1|web      |
1|web      | SyntaxError: Invalid or unexpected token
1|web      |     at Object.compileFunction (node:vm:360:18)
1|web      |     at wrapSafe (node:internal/modules/cjs/loader:1126:15)
1|web      |     at Module._compile (node:internal/modules/cjs/loader:1162:27)
1|web      |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
1|web      |     at Module.load (node:internal/modules/cjs/loader:1076:32)
1|web      |     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
1|web      |     at Object.<anonymous> (C:\Users\EDY\AppData\Roaming\nvm\v16.20.2\node_modules\pm2\lib\ProcessContainerFork.js:33:23)
1|web      |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
1|web      |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
1|web      |     at Module.load (node:internal/modules/cjs/loader:1076:32)

```

at last : I can run api server
but could run web server

even though use yarn start
```shell
$ npm run dev

Compiled successfully!

You can now view gsg-boilerplate in the browser. 

  Local:            http://localhost:3000        
Compiled successfully!

You can now view gsg-boilerplate in the browser. 

  Local:            http://localhost:3000        
  On Your Network:  http://192.168.0.100:3000    

Note that the development build is not optimized.
To create a production build, use yarn build. 
```

but couldn't open  http://localhost:3000

**Comment by IOLOII** [comment]
here is pm2 log

```shell

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1126:15)
    at Module._compile (node:internal/modules/cjs/loader:1162:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Object.<anonymous> (C:\Users\EDY\AppData\Roaming\nvm\v16.20.2\node_modules\pm2\lib\ProcessContainerFork.js:33:23)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
C:\USERS\EDY\DOCUMENTS\REPOS\GSG-BOILERPLATE\NODE_MODULES\.BIN\REACT-SCRIPTS.CMD:1
@IF EXIST "%~dp0\node.exe" (
^

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1126:15)
    at Module._compile (node:internal/modules/cjs/loader:1162:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Object.<anonymous> (C:\Users\EDY\AppData\Roaming\nvm\v16.20.2\node_modules\pm2\lib\ProcessContainerFork.js:33:23)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
C:\USERS\EDY\DOCUMENTS\REPOS\GSG-BOILERPLATE\NODE_MODULES\.BIN\REACT-SCRIPTS.CMD:1
@IF EXIST "%~dp0\node.exe" (
^

```

**Comment by vincentdesmares** [comment]
Hi @IOLOII ,

`C:\Users\EDY\.pm2\logs\web-error.log last 15 lines:` : it looks like you are running this script natively on a Windows system. Right now the scripts from GSG are only compatible with an Unix system, as Linux or MacOS.

You should try to install windows subsystems!

Yet we did not intend to create anything specific to a Unix system, so maybe the error can be fixed without too much hassle. I see that the error comes from`REACT-SCRIPTS.CMD`, maybe looking at the create-react-app repository would direct you to a solution.

V.

**Comment by IOLOII** [comment]
> Hi @IOLOII ,
> 
> 
> 
> `C:\Users\EDY\.pm2\logs\web-error.log last 15 lines:` : it looks like you are running this script natively on a Windows system. Right now the scripts from GSG are only compatible with an Unix system, as Linux or MacOS.
> 
> 
> 
> You should try to install windows subsystems!
> 
> 
> 
> Yet we did not intend to create anything specific to a Unix system, so maybe the error can be fixed without too much hassle. I see that the error comes from`REACT-SCRIPTS.CMD`, maybe looking at the create-react-app repository would direct you to a solution.
> 
> 
> 
> V.

Ok, I will try later

**Comment by IOLOII** [comment]
> Hi @IOLOII ,
> 
> `C:\Users\EDY\.pm2\logs\web-error.log last 15 lines:` : it looks like you are running this script natively on a Windows system. Right now the scripts from GSG are only compatible with an Unix system, as Linux or MacOS.
> 
> You should try to install windows subsystems!
> 
> Yet we did not intend to create anything specific to a Unix system, so maybe the error can be fixed without too much hassle. I see that the error comes from`REACT-SCRIPTS.CMD`, maybe looking at the create-react-app repository would direct you to a solution.
> 
> V.

yes, you're right
